name: Artifacts Demo
on: 
    workflow_dispatch:
jobs:
    job1:
       name: Upload Artifact
       runs-on: ubuntu-latest
       steps:
            - name: "creating local file"
              run: |
                echo "Hello World,How are you today?" > hello.txt
            - uses: actions/upload-artifact@v2
              with:
                name: file
                path: file.txt
                retention-days: 10
    job2:
        name: Download Artifact
        runs-on: ubuntu-latest
        needs: job1
        steps:
           - name: Download Artifact
             uses: actions/download-artifact@v2
             with:
                name: file
           - name: Printing the file content
             run: |
               cat file.txt