# This is basic demo to get started with github actions
name: A basic demo of github actions

# Controls when the action will run.
on:
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
        - name: checkout the code
          uses: actions/checkout@v3

        - name: Run single command using the runner shell
          run: echo "Hello,This is a basic demo of github actions.!"
        - name : Run multiple commands
          run: |
            echo "First command basic of github actions!"
            echo "deploy and test you project!"
   build-api:
    runs-on: windows-latest
    steps:
      - name: build-api
        run: echo "Building API"
  