name: deployment
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: check Nodejs version
        run: npm version
      - name: display nodejs version
        run: node --version
      - name: Run ls -lrt
        run: ls -lart